GoogleCloudPlatform/osconfig

ospatch/patch_run.go, ospatch/system_linux.go, ospatch/system_windows.go, ospatch/updates_linux.go, ospatch/updates_windows.go
Actually add new patch run to state when they are acked
Fix issue with needs-restarting on el6
Be smarter about running shutdown on Windows.
=> Fix a few bugs in patch

config/config.go, inventory/inventory.go, inventory/packages/apt_deb.go, inventory/packages/packages_linux.go, inventory/packages/packages_windows.go, inventory/packages/wua_windows.go, inventory/packages/yum.go, inventory/packages/zypper.go, main.go, ospatch/patch_run.go, ospatch/patch_state_test.go, ospatch/updates_linux.go, ospatch/updates_windows.go, packaging/build_packages_rpm.sh
Yum and Apt settings are now respected for patch runs
Inventory logs debug instead of info
Inventory reads from apt-get full-update
Cleaned up Windows WUA logging
Patch run steps now automatically log
Only retry on certain API errors
=>  Respect apt and yum special options for patch + bug fixes

inventory/packages/apt_deb.go, inventory/packages/gem.go, inventory/packages/googet.go, inventory/packages/pip.go, inventory/packages/rpm.go, inventory/packages/yum.go, inventory/packages/zypper.go, main.go, packaging/build_packages_wf.json, packaging/daisy_startupscript_rpm.sh, packaging/google-osconfig-agent.spec
Fixed bugs:
Running inventory right after EL boot could cause a panic because of a yum output line matching enough checks and then an unchecked index
APT updates can have multiple repos they exist in, fixed parsing to allow for this
Tests coming for inventory functions in follow up PR
=> Fix a few inventory bugs, add EL8 build

packaging/common.sh, packaging/debian/changelog, packaging/google-osconfig-agent.spec
preparing for release in images
=> version bump

google-osconfig-agent.service, inventory/packages/packages.go, inventory/packages/packages_linux.go, inventory/packages/zypper.go, inventory/packages/zypper_test.go, packaging/common.sh, packaging/debian/changelog, packaging/googet/google-osconfig-agent.goospec, packaging/googet/install.ps1
Bump version,
Fix systemd service file to work with older versions of systemd
=> Add ZypperPatches to inventory

policies/recipes/steps.go
Check exit codes, remove unnecessary quoting, standardize interpreter handling
=> Update shebang and arg handling

policies/policies.go
following changes to lookupeffectiveguestpolicies, we can now enable recipe running. runs strictly after package/repo, but behaves similarly. errors at the recipe level are logged but don't block.
=> enable software recipes

packaging/common.sh, packaging/daisy_startupscript_deb.sh, packaging/daisy_startupscript_goo.sh, packaging/debian/changelog
the upgrade process is extremely variable and produces an inconsistent build workflow
=> no upgrade in deb build

policies/recipes/installrecipe.go, policies/recipes/steps.go
Stacked PR - only first commit
Set filecopy default permissions
Remove working directory after recipe install
Remove fmt.Printf calls
=> SWR remove working directory after run

external/fetcher.go, ospatch/exec_step.go, policies/recipes/artifacts.go, policies/recipes/recipedb.go, policies/recipes/steps.go
two small bugs I found while working on the end to end tests.
=> small bugfixes

ospatch/exec_step.go
=> no logging if there is no pre-/post-patch step output

agentendpoint/agentendpoint.go, agentendpoint/agentendpoint_test.go, agentendpoint/exec_task.go, agentendpoint/patch_task.go, agentendpoint/retry.go, agentendpoint/task_state.go, agentendpoint/task_state_test.go, config/config.go, tasker/tasker.go
This does not contain any patch or exec system code yet, just the basic api interactions and basic logic.
=> Add basic agentendpoint logic

ospatch/apt_upgrade.go, ospatch/googet_update.go, ospatch/runner.go, ospatch/system_linux.go, ospatch/system_test_stub.go, ospatch/system_windows.go, ospatch/updates.go, ospatch/updates_linux.go, ospatch/updates_test.go, ospatch/updates_test_stub.go, ospatch/updates_windows.go, ospatch/yum_update.go, ospatch/zypper_patch.go
This is essentially a straight copy/paste with some bits pulled out. Those will be added back in in a subsequent PR connecting the task execution code to patch
=> Fork ospatch to work with agentendpoint

agentendpoint/patch_linux.go, agentendpoint/patch_task.go, agentendpoint/patch_windows.go, agentendpoint/reboot_linux.go, agentendpoint/reboot_windows.go
Much of this is simply a copy/paste from the existng ospatchog code tweaked to run via agentendpoint tasks.
=> Connect agentendpoint and ospatch

e2e_tests/osconfig_server/osconfig_data_builder.go, e2e_tests/test_suites/guestpolicies/guest_policies.go, e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go, e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
Close to a copy paste from:
https://github.com/GoogleCloudPlatform/compute-image-tools/pull/949
=> Add SoftwareRecipe tests

policies/local.go, policies/local_test.go, policies/policies.go
TESTED: Ran the locally-built osconfig on a VM, verified that a recipe from metadata is being applied.
=> Activated the local software configs feature

config/config.go, e2e_tests/test_suites/guestpolicies/guest_policies.go, e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go, e2e_tests/test_suites/patch/patch.go, inventory/packages/apt_deb.go, inventory/packages/packages.go, inventory/packages/rpm.go, inventory/packages/zypper.go, policies/local.go, policies/recipes/artifacts.go, policies/recipes/installrecipe.go, policies/recipes/steps.go, util/util.go
Add DpkgInstallation and RpmInstallation step types to software recipes 
Add test for DpkgInstallation and RpmInstallation
Clean up some command line args to be more verbose
Fix zip file extraction on Windows
=> Update software recipes

e2e_tests/test_config/project_config.go, e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go, e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
Fix a few bugs with centos/rhel tests
=> Update e2e tests

e2e_tests/utils/utils.go, go.mod, go.sum
2008R2 and 1803 are EOL, drop them from tests, add 1909
=> Update Windows test images

config/config.go, google-osconfig-agent.service
=> Fix typo and systemd service file

agentendpoint/patch_task.go, e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go, e2e_tests/test_suites/inventory/test_setup.go, e2e_tests/test_suites/patch/test_setup.go, main.go
Disable auto updates if TaskNotificationEnabled is set in main loop.
=> Use e2 machine types for tests, disable auto updates

agentendpoint/patch_windows.go, inventory/inventory_test.go, inventory/packages/packages.go, inventory/packages/wua_windows.go, main.go, ospatch/updates_windows.go, packaging/googet/google-osconfig-agent.goospec
Rework wua interface to ensure we free memory as needed
Run debug.FreeOSMemory() at the end of each cycle to unused memory to ensure our footprint doesn't keep increasing.
Add profile flag
=> Be more proactive with memory management

config/config.go, config/config_test.go, main.go
currently, the agent config is polled at the same frequency as the inventory or guestpolicy run. The current default is 10 mins. So, when a customer enables our service customers have to wait for 10mins before they can see any change.
Decoupled the servicepoll interval from metadapoll interval. Also, currently not allowing customers to change the metadata poll interval since this is agent's property. We can decide if we want customers to be able to specify their own poll interval.
log enabled feature. sample log
Apr 16 10:06:14 debian-tmux-setup OSConfigAgent[12234]: 2020-04-16T10:06:14.1932Z OSConfigAgent Info: OSConfig enabled features status:{GuestPolicies: false, OSInventory: true, PatchManagement: true}
=> poll agent config more frequently

agentendpoint/agentendpoint.go, agentendpoint/agentendpoint_beta.go, agentendpoint/patch_beta_linux.go, agentendpoint/patch_beta_windows.go, agentendpoint/patch_linux.go, agentendpoint/patch_windows.go, policies/policies.go, retryutil/retry.go
- refactored out retry utility functions, so that they can be used in other part of the applications
- Added retries to guestpolicy operations
=> Handle transient failures in guestpolicy operations

e2e_tests/test_suites/patch/patch.go
- If this helps, I'll add it to more APIs.
- also fixes minor bug from previous PR
=> Add retry to test APIs

agentendpoint/patch_beta_linux.go, agentendpoint/patch_linux.go
=> fix excludes and exclusive-includes for apt, yum and zypper

packages/packages.go, packages/wua_windows.go
=> merge from master

main.go, main_windows.go, packages/wua_windows.go
Used Application Verifier from Windows SDK to evaluate heap leaks
Also reorganized and how we call mains deferred functions so we actually log the shutdown call to cloud logging.
=> Rework COM object memory management

packages/packages_windows.go, packages/wua_windows.go
Simplify session creation
Add more context to errors
=> Update WUA session creation and error logging

config/config.go, config/config_test.go, config/package_resouce.go, packages/msi.go, packages/packages.go, policies/policies.go
Validate fully implemented and unit tested
Check state still needs unit tests as well as implementation for msi/deb/rpm packages.
=> Add validate and check state functionality for PackageResource

agentconfig/agentconfig.go, config/config.go, config/config_test.go, config/package_resource.go, config/package_resource_test.go, config/repository_resource.go, config/repository_resource_test.go
Still need to add tests for APT GPG key setup, this should be a feature match for current GuestPolicies.
=> Add RepositoryResource

agentendpoint/inventory.go
=> add debug logging for report inventory response

agentendpoint/config_task.go, agentendpoint/config_task_test.go, agentendpoint/exec_task.go, config/config.go, config/file.go, config/file_resource.go, config/file_resource_test.go, config/package_resource.go, config/repository_resource.go, external/fetcher.go, go.mod, policies/recipes/artifacts.go, util/util.go
Added FileResource logic and unit tests
Slight reorganization of existing code (naming and function location)
Added a "Cleanup" step to all config resources, currently only FileResource actually uses this
=> Add FileResource

agentendpoint/agentendpoint.go, agentendpoint/agentendpoint_test.go
=> Add sleep after Unavailable errors for agentendpoint

config/file_resource.go, config/package_resource.go, config/package_resource_test.go, packages/apt_deb.go, packages/apt_deb_test.go, packages/packages_linux.go, packages/rpm.go, packages/rpm_test.go
Merged latest two commits from master as one was related to the code I was changing.
=> Support deb and rpm in PackageResource

agentconfig/agentconfig.go, agentendpoint/inventory.go, e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
Also made a minor update to the inventory reporting e2e test verification logic
/assign @adjackura @paulseawa 
/woof
=> remove feature flag for inventory reporting

agentendpoint/agentendpoint.go, agentendpoint/inventory.go, e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
=> add additional debug logging for ReportInventory request payload for e2e tests

agentendpoint/inventory.go
The logic tracks an additional number of "attempts" for reporting full inventory to prevent going into an infinite loop in case service continuously keeps asking for full inventory. Otherwise, each ReportInventory call (with full inventory or not) gets retried according to the retryutil specifications.
/hold Tested manually but still need to run e2e tests
/assign @adjackura @jaiminsh 
/woof
=> use retryutil for ReportInventory call

e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
Tested by running all tests in the `OSInventoryReporting` suite.
/woof
/assign @adjackura
=> update ReportInventory e2e test regexes

packages/cos.go, packages/cos_stub.go, packages/cos_test.go
=> Fix builds for ppc and s390x

packages/cos.go, packages/cos_stub.go, packages/cos_test.go
=> Simplify build tags for COS package

policies/recipes/steps.go, util/util.go
File.Chmod does not work on Windows, so instead create the temp file with the wanted permissions
=> Create util.TempFile to work nicely with Windows

config/config.go, config/exec_resource.go, config/exec_resource_test.go
More unit tests still need to be added for the rest of the ExecResource
=> Fix ExecResource for config task, add minimal unit test

e2e_tests/test_suites/guestpolicies/guest_policies.go, e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go, e2e_tests/test_suites/ospolicies/ospolicies.go, e2e_tests/test_suites/ospolicies/ospolicies_test_data.go, e2e_tests/utils/utils.go
Added package removal OSPolices test
Added package install from new repo OSPolices test
Added sles OSPolices tests
Update tests names for both GuestPolices and OSPolices
=> e2e_tests: Add more OSPolicies package and repo tests

e2e_tests/test_suites/inventory/inventory.go, e2e_tests/test_suites/inventoryreporting/inventory_reporting.go, e2e_tests/test_suites/ospolicies/ospolicies.go, e2e_tests/utils/utils.go
Fix inventory poll interval
Wait for policy assignment rollout to complete
Delete old inventory metadata report
=> Fix e2e_tests

e2e_tests/test_suites/ospolicies/ospolicies.go, e2e_tests/test_suites/ospolicies/ospolicies_test_data.go, e2e_tests/test_suites/ospolicies/ospolicies_utils.go, e2e_tests/utils/utils.go
Also start using the operations service.
=> e2e_tests: add ExecResource tests

e2e_tests/test_suites/ospolicies/ospolicies.go, e2e_tests/test_suites/ospolicies/ospolicies_test_data.go, e2e_tests/test_suites/ospolicies/ospolicies_utils.go, e2e_tests/utils/utils.go
Start testing in staging
Correct a few suse tests setup
Correct Windows ExecResource tests
Drop EL6 support (os is EOL) unless tests explicitly load it
=> e2e_tests: fixup OSPolicy tests, start testing in staging

agentconfig/agentconfig.go, agentendpoint/agentendpoint.go, config/repository_resource.go, config/repository_resource_test.go, e2e_tests/test_suites/ospolicies/ospolicies.go
=> Remove pre-release flag from config

e2e_tests/test_suites/ospolicies/ospolicies.go
Dropped timeout to 20min, longest test takes just over 13min it seems (including zone wait time)
Add locking with delete call to somewhat limit qps
=> e2e_tests: re-add retries to OSPolicies

agentconfig/agentconfig.go, agentendpoint/config_task.go, agentendpoint/exec_task.go, agentendpoint/inventory.go, agentendpoint/task_state_test.go, clog/clog.go, config/file_resource.go, config/package_resource.go, config/repository_resource.go, go.mod, go.sum, ospatch/apt_upgrade.go, ospatch/yum_update.go, ospatch/zypper_patch.go, packages/packages.go, packages/yum.go, tasker/tasker.go
https://pkg.go.dev/golang.org/x/tools@v0.1.0/go/analysis/passes/fieldalignment
=> Run fieldalignment on all structs

examples/OSPolicyAssignments/console/setup_repo_and_install_package_linux_apt.yaml
Just updating an incorrect comment.
=> chore: Fixing a comment.

examples/Terraform/README.md
Its first use will be to contain the example scripts illustrating how to create
Guest Policies and OS Policies in multiple GCP projects.
=> Add examples/Terraform directory.

agentendpoint/inventory.go, agentendpoint/inventory_test.go
Map deb to apt based on apt existing
Map rpm to zypper or yum based on those package systems existing
=> Fix rpm/deb package formating for inventory reporting

packages/pty_linux.go
* changed the runWithPty function to use child's stdin for the
controlling terminal - this is what the exec package expects
* changed handling of errors returned by cmd.Run not to ignore all
errors
* changed the error return statements to return std{in,err} instead of
nil because these can be useful for troubleshooting errors
=> Fixed the runWithPty function to set ctty to child's filedesc

ospatch/apt_upgrade.go, ospatch/report.go, ospatch/yum_update.go
This is a demo for Yum and Apt, if this looks good I'll update the rest of the package managers, PTAL
=> Added patch report log messages for Yum and Apt

e2e_tests/test_suites/inventory/inventory.go, e2e_tests/test_suites/patch/patch.go, e2e_tests/utils/utils.go
Modify inventory test to combine tests into one test case
Add retries to patch tests
Add debian-11 and windows 2020 to tests
=> e2e_tests: update OS targets, adjust retries

packages/apt_deb.go, packages/apt_deb_test.go
When apt-get calls fails because of a package downgrade, try again with --allow-downgrades flag
Downgrading is a default behavior for many package managers even apt (just apt not apt-get command) and should be considered the same way as upgrading a package in terms of safety concerns.
=> Add --allow-downgrades flag to apt-get calls

examples/OSPolicyAssignments/console/win-ensure-openssh.yaml, examples/OSPolicyAssignments/gcloud/win-ensure-openssh.yaml
Hi,
This is an example OS policy referenced in an upcoming blog post, it would be great to add it to the example set.
Any queries please let me know.
All the best,
Alex
=> example policy to ensure sshd is running on windows VMs

agentendpoint/exec_task.go, policies/recipes/artifacts.go
Some low hanging fruits with not closed clients
=> Close clients that are not passed anywhere

config/package_resource_test.go, ospatch/yum_update_test.go, packages/apt_deb_test.go, packages/googet_test.go, packages/rpm_test.go, packages/yum_test.go, packages/zypper_test.go, util/mocks/match.go
=> Fix comparing exec.Cmd in mock on Go1.20

e2e_tests/utils/utils.go
The image project was incorrect. Verified VM creation via gcloud.
=> Update old SLES images paths

agentendpoint/agentendpoint.go
Current code have 11 attempts rather than 10, log with 11 of 10 attempts a bit misleading, i don't think one more attempt make sense.
=> Fix condition to have 10 attempts rather than 11.

e2e_tests/test_suites/guestpolicies/guest_policies_utils.go, e2e_tests/test_suites/inventory/test_setup.go, e2e_tests/test_suites/inventoryreporting/test_setup.go, e2e_tests/test_suites/patch/test_setup.go, e2e_tests/utils/utils.go
Fixing failing e2e tests. Removing old OS images that no longer exist. Adding new images and releases.
=> Removing obsolete OS images and adding new ones

e2e_tests/utils/utils.go
Fix so they fix in the 63 characters long constraint
=> Shortening the reported image names

packages/yum.go, packages/yum_test.go
=> Fix parse yum updates to consider the packages under 'installing dependencies' keyword

README.md
This change doesn't do anything except trigger a build pipeline so the agent can be released
=> Some change to create an agent release

e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
=> Fix SUSE package update e2e tests to use another existing package

config/exec_resource.go, e2e_tests/test_suites/guestpolicies/guest_policies_utils.go, policies/recipes/steps.go
=> GuestPolicies e2e: Remove ed package if exist for zypper startup_script in recipe-steps tests

examples/OSPolicyAssignments/console/google-cloud-sap-agent.yaml, examples/OSPolicyAssignments/gcloud/google_cloud_sap_agent.yaml
Adds a console and gcloud example policies that will:
* Add the agents package repo
* Install the agent if it's not already installed
* Update the agent to the latest version
=> Adds a console and gcloud example policies

OWNERS
=> Update OWNERS file to replace mahmoudn GitHub username by personal email GitHub username

e2e_tests/utils/utils.go
=> Removed debian-10 from e2e tests

packagebuild/README.md, packagebuild/common.sh, packagebuild/daisy_startupscript_deb.sh, packagebuild/daisy_startupscript_goo.sh, packagebuild/daisy_startupscript_rpm.sh, packagebuild/test_build.sh, packagebuild/workflows/build_deb10.wf.json, packagebuild/workflows/build_deb11.wf.json, packagebuild/workflows/build_deb11_arm64.wf.json, packagebuild/workflows/build_deb12.wf.json, packagebuild/workflows/build_deb12_arm64.wf.json, packagebuild/workflows/build_el6.wf.json, packagebuild/workflows/build_el7.wf.json, packagebuild/workflows/build_el8.wf.json, packagebuild/workflows/build_el8_arm64.wf.json, packagebuild/workflows/build_el9.wf.json, packagebuild/workflows/build_el9_arm64.wf.json, packagebuild/workflows/build_goo.wf.json, packagebuild/workflows/build_package.wf.json
As part of osconfig-agent pipeline migration, this PR copy packagebuild folder from guest-test-infra repo to osconfig repo.
/cc @dowgird
=> Copy packagebuild folder from guest-test-infra repo to osconfig repo

packagebuild/workflows/build_deb12.wf.json, packagebuild/workflows/build_deb12_arm64.wf.json
=> Fix Debian-12 package build workflow typo

.github/dependabot.yml
Covers direct & indirect dependencies
=> Dependabot dependency updates

packagebuild/workflows/build_deb12.wf.json, packagebuild/workflows/build_deb12_arm64.wf.json
=> Update Debian-12 package build workflow to use debian-cloud project

.github/workflows/codeql.yml
Resolving the issue with Default configuration not found on PRs.
=> Adding advanced CodeQL settings to scan on PRs

e2e_tests/utils/utils.go
=> Add a temporary e2e test image for Ubuntu to test the latest osconfig-agent stable version

e2e_tests/test_suites/guestpolicies/guest_policies_utils.go, e2e_tests/test_suites/inventoryreporting/test_setup.go, e2e_tests/test_suites/ospolicies/ospolicies_utils.go, e2e_tests/utils/utils.go
=> E2e tests: install gnupg2 and run apt update in VMs startup-scripts

e2e_tests/utils/utils.go
=> E2e tests: use family url format instead of specific version url for head test images

e2e_tests/utils/utils.go
=> E2e tests: Fix EL version detection logic in E2E tests

e2e_tests/utils/utils.go
=> E2e tests: allow passing spesific EL version number to InstallOSConfigEL func

e2e_tests/test_suites/guestpolicies/guest_policies_utils.go, e2e_tests/test_suites/inventory/test_setup.go, e2e_tests/test_suites/inventoryreporting/test_setup.go, e2e_tests/test_suites/ospolicies/ospolicies_utils.go, e2e_tests/test_suites/patch/test_setup.go, e2e_tests/utils/utils.go
/assign @burov 
/cc @burov 
/cc @dowgird
=> Update Apt e2e tests to pull osconfig-agent pkg from new AR repos instead of rapture

examples/OSPolicyAssignments/console/CIS/cis-exclude-check-once-a-day.yaml, examples/OSPolicyAssignments/console/CIS/cis-level1-once-an-hour-policy.yaml, examples/OSPolicyAssignments/console/CIS/cis-level2-once-a-day-policy.yaml
This PR updates the remaining policy examples.
=> Update to the CIS OS policy samples

e2e_tests/utils/utils.go
Typo from last PR
/cc @dowgird
=> fix SUSE e2e tests

e2e_tests/utils/utils.go
The main goal is to install a new test grid for executing tests on the testing (autopush) pkgs.
/cc @dowgird
=> Allow Windows e2e tests to pull osconfig-agent pkg from testing (private) repos from Artifact registry

e2e_tests/utils/utils.go
=> Disable centos-stream-8 tests as it reached EOL in May 31

e2e_tests/utils/utils.go
=> Fix the logic of pick region for Artifact Registry function

e2e_tests/utils/utils.go
=> Disable SUSE tests to run with testing agent repo

e2e_tests/utils/utils.go
=> Update e2e tests to use VMM team's GCP project for pkgs testing version

packages/apt_deb.go, packages/apt_deb_test.go
Fitler out all packages that have other status than `installed`
=> Fix(dpkg) return onlt installed items as inventory

e2e_tests/utils/utils.go
=> Update old SLES images urls

packagebuild/README.md
=> Pipeline testing 00

e2e_tests/utils/utils.go
=> Enable gpgcheck flag for RPM e2e tests

e2e_tests/test_suites/ospolicies/ospolicies_test_data.go, e2e_tests/test_suites/ospolicies/ospolicies_utils.go
Use gcsfuse pkg instead of google-chrome for test
/cc @dowgird
/cc @MarcMarc
=> Fix SLES-12 SP5 RPM package-resource e2e test

config/file_resource.go, config/file_resource_test.go, config/repository_resource.go, config/repository_resource_test.go, packages/zypper.go
=> Add debugging logs for repository resource config

e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
/assign @MarcMarc
/cc @dowgird
=> Disable Repository Resource test for SLES-12

e2e_tests/test_suites/inventoryreporting/test_setup.go, e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
/assign @MarcMarc
/cc @MarcMarc
=> Replace osconfig-agent-test pkg by gcsfuse in ospolicies tests and inventory-report tests

e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go, e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
/assign @MarcMarc
/cc @MarcMarc
=> Use gcsfuse pkg in guest-policies e2e in pkg update tests instead of old pkgs

go.mod
See: https://github.com/golang/go/issues/61888
=> Fix golang version format to fix builds.

presubmit_packagebuild/Dockerfile, presubmit_packagebuild/main.sh
=> Move packagebuild presubmit to osconfig

e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go, e2e_tests/test_suites/ospolicies/ospolicies_test_data.go, e2e_tests/test_suites/ospolicies/ospolicies_utils.go
* change deprecated package to valid one
=> Fix e2e tests

e2e_tests/test_suites/inventoryreporting/test_setup.go
Change available package to fix test.
=> change available package

go.mod
fixes broken [build-testing-pkgs-pipeline](https://louhi.dev/6392207713632256/execution-detail/5401414326419456)
=> `go mod tidy` after go/x/crypto update 0.32.0 -> 0.37.0

agentconfig/agentconfig.go, inventory/inventory.go, packages/trace.go, util/utiltrace/utiltrace.go, util/utiltrace/utiltrace_test.go
when "trace-get-inventory" metadata flag is enabled
=> Trace GetInstalledPackages memory levels
