GoogleCloudPlatform/osconfig

- config/config.go
- google-osconfig-agent.service
- main.go
- packaging/build_packages_wf.json
- packaging/common.sh
- packaging/debian/changelog
- packaging/debian/postrm
- packaging/debian/rules
- packaging/googet/google-osconfig-agent.goospec
- packaging/googet/install.ps1
- packaging/google-osconfig-agent.spec
- tasker/tasker.go
Agent now reacts to restart required signal and stops, the various service managers handle the restart automatically.
> Don't restart service on package upgrade

- policies/OWNERS
This file is additive; it will add one approver to existing, only for files below policies/ directory.
> add liam as guest policies approver

- ospatch/patch_run.go
This is to show that the order of steps will be STARTED -> (pre-patch reboot if any) -> RUNNING_PRE_PATCH_STEP -> APPLYING_PATCHES -> (post-patch reboot if required) -> RUNNING_POST_PATCH_STEP -> SUCEEDED.
Manually verified that debug logs show up when they should.
/woof
/assign @adjackura @ryanwe
> add empty pre-/post-patch steps to patch run

- common/common.go
- packaging/README.md
- policies/recipes/artifacts.go
- policies/recipes/steps.go
so that they can be used for patching too
Tests done:
- `go build`
- `go test ./...`
/woof
> move artifact fetching logic to common

- common/common.go
- ospatch/exec_step.go
- ospatch/exec_step_linux.go
- ospatch/exec_step_windows.go
- ospatch/patch_run.go
- There are debug logs for agent actions and info log for step execution output
- Will download GCS object as a file to the same directory (update: now the temporary directory) as the agent, execute it from within the same directory, then remove it
/woof
/assign @adjackura @ryanwe @hopkiw
> add pre-/post-patch step execution for linux and windows

- policies/recipes/steps.go
I don't know how it got from decimal 755 to the permissions that you saw but from testing it looks like switching it to octal fixes the issue.
> switching default permission constant to be specified in octal

- attributes/attributes.go
- attributes/attributes_test.go
- config/config.go
- config/config_test.go
- tasker/tasker.go
- tasker/tasker_test.go
Improve coverage for unit test
- Add unit test for config, attributes, tasker package
- Fix bug in tasker:
The tasker would never stop because the underlying channel
was never closed and this the tasker waited on the channel
forever
------------------------------------------------------------------------------
Coverage Before
------------------------------------------------------------------------------
?       github.com/GoogleCloudPlatform/osconfig [no test files]
?       github.com/GoogleCloudPlatform/osconfig/attributes      [no test files]
?       github.com/GoogleCloudPlatform/osconfig/common  [no test files]
ok      github.com/GoogleCloudPlatform/osconfig/config  0.067s  coverage: 70.0% of statements
ok      github.com/GoogleCloudPlatform/osconfig/inventory       0.078s  coverage: …
> Add more Unit tests

- policies/recipes/installrecipe.go
- policies/recipes/recipe.go
- policies/recipes/recipe_test.go
- policies/recipes/recipedb.go
Stacked PR, view latest commit only
Corrects 'assignment to nil map' RTE
Resulting on-disk JSON is e.g. `[{Name: "recipe_name", Version: "0", ...}, { ... } ]`
This isn't strictly valid JSON as top level isn't an object, but the marshaling functions don't mind.
> Fix recipeDB init

- ospatch/exec_step.go
- ospatch/exec_step_linux.go
- ospatch/exec_step_windows.go
FetchGCSObject helper was refactored since the first commit of exec step logic which caused a nil pointer issue.
Testing done:
- `go test ./...`
- gcloud and manual agent installation on instance
/assign @adjackura @iamsubratp 
/woof
> Fix exec step GCS object fetching

- agentendpoint/patch_linux.go
- inventory/packages/apt_deb.go
- inventory/packages/apt_deb_test.go
- inventory/packages/packages_linux.go
- ospatch/apt_upgrade.go
- ospatch/googet_update.go
- ospatch/system_linux.go
- ospatch/system_windows.go
- ospatch/updates.go
Includes name may/probably will change in the future.
All package management functions for GooGet and APT moved to the 'packages' package from ospatch
Packages to be updated are now evaluated, logged, then installed
Dryrun option does everything up to actually install new packages.
APT logic updated to support both dist/full and normal upgrades
Logging package has been updated so logging initialization changed slightly
> Add beginnings of includes/excludes for package management

- inventory/packages/apt_deb.go
- inventory/packages/apt_deb_test.go
- inventory/packages/wua_windows.go
Some apt packages can have a trailing empty bracket that should be ignored
> Apt parsing and WUA library fixes

- inventory/packages/zypper.go
- inventory/packages/zypper_test.go
- ospatch/apt_upgrade.go
- ospatch/updates.go
- ospatch/zypper_patch.go
--with-update is a tricky case to handle with patches. All the other fields/flags in zyppersettings work on patches except for --with-update, which runs on packages.
readmore: https://www.mankier.com/8/zypper#--with-update
Here is the algorithm to prepare patch and package list for zypper:
- Fetch the list of patches with the filters on severity, category
- If user specifies --with-update, fetch the list of packages that will be updated.
- Filter out any package that will be updated as a part of a patch install from the list of packages to be updated;
- to know packages are going to be updated as a part of a patch, we have used "zypper info -t " command
-  for the list of excluded patches specified by user, filter out the patches from the previously generated patch list.
> Implement patch whitelisting for zypper

- e2e_tests/go.sum
- e2e_tests/test_suites/patch/patch.go
- ospatch/zypper_patch.go
- ospatch/zypper_patch_test.go
- since our e2e_tests for patch with specific functionality only tests that the specific fields does not break the agent, did some refactoring in zypper patch and added unit tests which is more suitable to testing the filter logic for the specific fields.
- during test runs, found a bug in zypper filters; fixed the bug
- added e2e test that exercises the e2e code path for specific features; again, we only verify that the code path does not break anything. the reliability of functional correctness of the code path is achieved by unit tests
> Add tests for patch whitelisting

- e2e_tests/utils/utils.go
the old images were created in compute-image-osconfig-agent; instead it should have been created in compute-image-tools-test.
created the image now.
> update sles image project name

- e2e_tests/compute/instance.go
- e2e_tests/test_suites/guestpolicies/guest_policies.go
- e2e_tests/test_suites/inventory/inventory.go
- e2e_tests/test_suites/patch/patch.go
- packaging/debian/rules
This was causing way too much api traffic, instead just record the serial port output at the end of each test before we delete the instance.
> Don't stream serial port in e2e_tests

- packaging/debian/rules
Service file was being installed by build_deb.sh, so was omitted when we moved to new packagebuilder. The preset file was never being installed previously, apparently dh_installinit doesn't support it. Not that it mattered, since we don't call `systemctl preset`
dpkg-deb -c output:
```
drwxr-xr-x root/root         0 2020-01-10 20:35 ./
drwxr-xr-x root/root         0 2020-01-10 20:35 ./lib/
drwxr-xr-x root/root         0 2020-01-10 20:35 ./lib/systemd/
drwxr-xr-x root/root         0 2020-01-10 20:35 ./lib/systemd/system/
-rw-r--r-- root/root       351 2020-01-10 20:34 ./lib/systemd/system/google-osconfig-agent.service
drwxr-xr-x root/root         0 2020-01-10 20:35 ./lib/systemd/system-preset/
-rw-r--r-- root/root        36 2020-01-10 20:34 …
```
> Install systemd service and preset files in debian

- config/config.go
- config/config_test.go
- main.go
- packaging/debian/rules
- packaging/google-osconfig-agent.spec
Windows expects a quick signal that the service is started, waiting for metadata could slow that.
Waiting for metadata could prevent the agent from shutting down as quickly as it should (~15s), updated to wait on the canceled context.
Overall there should not be any major changes to startup, just code moved around.
> Update startup logic to prevent hanging

- e2e_tests/compute/instance.go
- e2e_tests/config/config.go
- e2e_tests/gcp_clients/gcp_clients.go
- e2e_tests/go.mod
- e2e_tests/go.sum
- e2e_tests/test_suites/guestpolicies/guest_policies.go
- e2e_tests/test_suites/inventory/inventory.go
- e2e_tests/test_suites/patch/patch.go
- e2e_tests/utils/utils.go
Instead of uploading directly to GCS, just save serial console output to the artifacts directory that our test wrapper uploads
> e2e_tests: Record serial output in artifacts

- agentendpointbeta/agentendpoint.go
- agentendpointbeta/agentendpoint_test.go
- agentendpointbeta/exec_task.go
- agentendpointbeta/exec_task_test.go
- agentendpointbeta/patch_linux.go
- agentendpointbeta/patch_task.go
- agentendpointbeta/patch_windows.go
- agentendpointbeta/reboot_linux.go
- agentendpointbeta/reboot_windows.go
- agentendpointbeta/retry.go
- agentendpointbeta/task_state.go
- agentendpointbeta/task_state_test.go
- policies/policies.go
Changes:
* forked the original package `agentendpoint` to be `agentendpointbeta`
* replaced v1beta imports in package `agentendpoint` with v1
* removed references to `LookupEffectiveGuestPolicy` from package `agentendpoint`
* made `policies.go` use `agentendpointbeta`
Tested with `go get cloud.google.com/go@master` -> `go build` -> `go test ./agentendpoint` -> `go test ./agentendpointbeta`
> create package agentendpointbeta and switch patch calls to use the v1 agentendpoint APIs

- packaging/debian/rules
- packaging/google-osconfig-agent.spec
As an example a EL7 build will be versioned something like 20200409.00-g1.el7
> Pass the package release into the build

- agentendpoint/patch_beta_windows.go
- agentendpoint/patch_windows.go
Don't return on first error, keep retrying unless we get a stop signal. Reduce retry number down to a more reasonable 10.
> Retry installing WUA updates until canceled or retries exceeded

- policies/recipes/steps.go
Changed created file permissions from 700 (`-w-rwxr--`) to 0700 (`rwx------`).
PoC:
```
dc@jhtc:~/gogo/chmod$ touch 700 0700
dc@jhtc:~/gogo/chmod$ cat chmod.go
package main
import "os"
func main() {
os.Chmod("700", 700)
os.Chmod("0700", 0700)
}
dc@jhtc:~/gogo/chmod$ go run chmod.go
dc@jhtc:~/gogo/chmod$ ls -la
total 12
drwxrwxr-x 2 dc dc 4096 Jun  9 17:37 .
drwxrwxr-x 7 dc dc 4096 Jun  9 17:36 ..
-rwx------ 1 dc dc    0 Jun  9 17:37 0700
--w-rwxr-- 1 dc dc    0 Jun  9 17:37 700
-rw-rw-r-- 1 dc dc   95 Jun  9 17:37 chmod.go
```
This might actually produce a security risk if there are other users on the system and the chmod'ed directory/file is accessible by them.
> Fix stepExecFile chmod permissions to 0700

- e2e_tests/test_suites/patch/patch.go
This should make it easier at a glance to understand why a patch job test failed.
> Log patch job after completion

- config/config.go
- config/config_test.go
without this, watchmetadata would return on any change in for this instance which this makes the agent logs a little spammy.
from now, the agent keeps a hash of the current agentconfig and only returns from watchconfig if there is anything that changes in the agentconfig.
> watch on osconfig specific metadata changes

- config/config.go
- config/config_test.go
with zonal agentendpoints, agents will now be talking to zonal agentendpoints.
the zonal endpoint is crafted by prefixing `osconfig-endpoint` metadata with the instancezone name.
The assumption here is that, zone value is always present in instancemetadata
referrred this
https://cloud.google.com/compute/docs/storing-retrieving-metadata#default
> make agent talk to zonal agentendpoint

- packaging/debian/rules
since we are already exluding the e2e_tests directory from getting built, there is no e2e_test binary created which results in failure of this command and breaks the overall build
tested with local build, here is the resulting files
subratp@agent-build:/tmp/debpackage-e$ dpkg -c google-osconfig-agent_1dummy-g1_amd64.deb
drwxr-xr-x root/root         0 2020-06-25 19:38 ./
drwxr-xr-x root/root         0 2020-06-25 19:38 ./etc/
drwxr-xr-x root/root         0 2020-06-25 19:38 ./etc/osconfig/
drwxr-xr-x root/root         0 2020-06-25 19:38 ./lib/
drwxr-xr-x root/root         0 2020-06-25 19:38 ./lib/systemd/
drwxr-xr-x root/root         0 2020-06-25 19:38 ./lib/systemd/system/
-rw-r--r-- root/root       321 2020-06-25 18:54 ./lib/systemd/system/google-osconfig-agent.service
drwxr-xr-x root/root …
> update rules to not include e2e test binary

- policies/policies.go
Larger sleep time makes the agent retry for long time. This results in longer wait time for subsequent tasks, sometimes resulting in timeouts.
> reduce number of retries for guest policy operations

- config/config.go
- main.go
Add an overall timeout for watchconfig and reduced the metadata watch timeout. this is to handle the case where agent is enabled and but the service is not enabled.
If there is no change in the metadata, the agent never gets a chance to establish a connection with the service.
the current timeout is 10 mins.
In the situtation mentioned above, it will take a total of 11 mins
also, removed the feature logging for now, since it will spam the serial console of vm incurring extra cost to customers. we will come up with a better plan for logging.
> add timeout to watchconfig

- agentendpoint/agentendpoint.go
- config/config.go
'break' does not stop the watch config. 'break' only breaks the inner most 'for', 'switch' or 'select'.
int64 are by automatically casted to duration type; which is equivalent to 10^-9 secs.
also, adding logging to show to the customers if the service is disabled. (not having this was misleading for me while testing.)
> fix watchconfig bug

- ospatch/yum_update.go
- ospatch/yum_update_test.go
- packages/packages.go
- packages/yum.go
- packages/yum_test.go
the agent uses `yum update --asssumeno` to get the list of update'ble packages. with version-locked packages, yum update thinks that it has to update the version-locked packages, which is a conflict and hence bails out the execution, eventually ending up in failed patch-jobs.
with this fix, customers can specify the version-locked packages in the list of excludes. This will end up in `yum update --assumeno` succeeding and also returning the list of update'ble packages excluding the version-locked packages.
Also, added unit tests for exclusive installs.
> make yum fetch updates with excludes

- clog/clog.go
- config/config.go
We need to actually wait for slow network bringup, make sure WatchMetadata doesn't loop faster than 5s, wait up to 60s for slow network
logger.Log has an incorrect default call depth of 2, my calculation based on this was therefore incorrect.
> Fix WatchMetadata web error handling, fix clog CallDepth

- osinfo/osinfo_linux.go
- osinfo/osinfo_windows.go
- packages/qfe_windows.go
Add more error details to WIndows inventory calls
Record osinfo details wven if some functions return errors.
Reorder windows osinfo functions in order of most likely to not return error.
> Fix panic if any osinfo calls fail

- agentendpoint/patch_windows.go
On a WUA error keep retrying for the full 10 cycles on any errors sleeping 60s between retries.
> Make sure we retry on failed Windows Updates

- agentendpoint/agentendpoint_beta.go
- go.mod
- go.sum
- packages/zypper_test.go
- policies/apt.go
- policies/googet.go
- policies/policies.go
- policies/yum.go
- policies/zypper.go
Set LookupEffectiveGuestPolicies retry time to 30s, this allows local configs to still run in a timely manner even if there is some service issue. Since GuestPolciies run every 10min they should get reapplied pretty soon anyway.
Cleaned up unneeded step of creating a blank repo file as the *Repositories functions will do that themselves
For GuestPolicies only gather package inventory when needed
> Cleanup policy code, set API retry time to 30s

- e2e_tests/compute/instance.go
- e2e_tests/go.sum
- e2e_tests/main.go
- e2e_tests/test_suites/inventory/inventory.go
- e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
- e2e_tests/test_suites/inventoryreporting/test_setup.go
- go.sum
Created a new test suite for inventory reporting. Test case does basic validations on the corresponding RPC invocation and its payload. Test setup was branched from the inventory test suite.
The WaitForSerialOutput verification function was referenced from https://github.com/GoogleCloudPlatform/osconfig/commit/9a3f7f3c83544dba6fbf4ecb0b6f1be6ad2dc693#diff-c54902af2d84c9ff1ed5525e24a7e3f3R52 and modified to support a list of regular expressions as one of the inputs.
/hold Waiting for the backend RPC visibility issue to be fixed.
/assign @adjackura @ryanwe 
/woof
> add initial e2e tests for inventory reporting

- agentconfig/agentconfig.go
- agentendpoint/inventory.go
- agentendpoint/inventory_test.go
- attributes/attributes.go
- attributes/attributes_test.go
- inventory/inventory.go
- main.go
- main_linux.go
- main_windows.go
- packages/packages_linux.go
- packages/packages_windows.go
We have issues with the WUA api leaking memory, this is an issue with the inventory calls because they run so often.  To solve this the list calls for inventory spawn a new instance of the agent to query the api, this is only implemented for inventory calls as patch calls do not run that often before an agent restart and the miniscule memory buildup per run will never be noticed.
Make sure we close clients when done with them.
The metadata unmarshal sometimes returns an error, this most often will be because of a bad send from the metadata server and can just be retried safely to avoid logging this error. (fixes #154)
> Make inventory WUAUpdates call spawn a new process, retry on metadata unmarshal error

- agentendpoint/exec_task.go
- agentendpoint/exec_task_test.go
When one sets an ExecStep for e.g. Linux while targeting both Linux and Windows VMs, the Windows VMs would still attempt to run the ExecTask and ultimately fail (i.e. `stepConfig` and `stepConfig.GetInterpreter()` before Line 153 evaluate to `nil` and `INTERPRETER_UNSPECIFIED` respectively). Unit tests were added to verify the new no-op behavior in those cases.
/assign @adjackura 
/woof
> complete ExecTask as no-op when the ExecStepConfig doesn't match the OS

- e2e_tests/utils/utils.go
Remove EOL 1809 image
Add 2004 image
Remove semiannual images from HEAD tests as they don't add much.
> Update test Windows images

- e2e_tests/utils/utils.go
Both are EOL, CentOS 6 repos do not exist and so no yum calls work
> Drop Windows 1903 and CentOS 6 from tests

- agentendpoint/config_task.go
- agentendpoint/config_task_test.go
Added additional debug log for printing each policy before execution
ConfigSteps will only contain the steps that ran for each resource
Logic change:
For each policy in policies:
- For each resource in this policies resources
- If management of a previous resource ended in failure, skip managing this resource
- Validate, setup, and check desired state
- Enforce desired state if required
- If enforcement was required record that post check state is required
If post check was triggered, check the state for every resource in each policy.
> config_task: Rework config step logic

- e2e_tests/test_suites/inventory/inventory.go
- e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
- main.go
On agent first start wait somewhere between 3 and 5 minutes before collecting inventory, after that collect inventory as normal.
Update inventory tests to account for this slow inventory start
Make sure we run RegisterAgent before any other actions.
> Gather inventory 3-5min after agent start

- agentconfig/agentconfig.go
The default HTTP client includes [Proxy: ProxyFromEnvironment](http://go/godoc/net/http/#RoundTripper). This change makes our http client work the same as it does in the [metadata library](https://github.com/googleapis/google-cloud-go/blob/v0.81.0/compute/metadata/metadata.go#L64-L71).
> Change metadata http client to ignore http proxies

- agentendpoint/config_task.go
- agentendpoint/config_task_test.go
When any resource is enforced mark all previous resources (for all policies) as needing post check.
With this change any resource that is evaluated AFTER the last resource that was "enforced" the agent will not re check.
> Config task: only run post check on resources that have already been evaluated

- e2e_tests/compute/instance.go
- e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
We no longer need to scrape serial output to determine of inventory was reported.
> e2e_tests: move to using inventory api for inventory reporting

- e2e_tests/test_suites/guestpolicies/guest_policies.go
- e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
- e2e_tests/test_suites/inventoryreporting/inventory_reporting.go
- e2e_tests/test_suites/inventoryreporting/test_setup.go
- e2e_tests/test_suites/ospolicies/ospolicies.go
- e2e_tests/test_suites/patch/test_setup.go
- e2e_tests/utils/utils.go
Move all linux tests to use e2-medium
Move all windows tests (other than patch) to e2-standard-2
Move all instances to use pd-balanced disks
Check inventory items for InventoryReporting tests
Rerun failed tests once to try to reduce flakes for a single test run
- inventory tests are not rerun as that setup was difficult to rerun simply, but they don't fail often
- both test cases will report on testgrid, if we don't like how that shows up we can instead not record the first failing test
> e2e_tests: reduce size of instances, use pd-balanced, rerun failed tests once

- e2e_tests/test_suites/ospolicies/ospolicies.go
- e2e_tests/test_suites/ospolicies/ospolicies_test_data.go
Tests are not particularly flaky so retries right now aren't very helpful and they are causing test run timeouts.
> e2e_tests: Don't retry failed OSPolicy tests, fix msi test

- agentendpoint/config_task.go
- config/exec_resource.go
Add debug log for full ApplyConfigTask dump
Add info log for starting each policy
Add info log for recording state for each resource
Allow for ExecResource to not have Enforce set (for example if policy is in VALIDATION mode)
> ConfigTask: add additional info logs

- config/exec_resource.go
- config/package_resource_test.go
- ospatch/yum_update_test.go
- packages/apt_deb.go
- packages/apt_deb_test.go
- packages/gem.go
- packages/googet_test.go
- packages/packages.go
- packages/qfe_windows.go
- packages/rpm_test.go
- packages/yum.go
- packages/yum_test.go
- packages/zypper.go
- packages/zypper_test.go
- util/util.go
Add better debug logging to DefaultRunner.Run()
> Use exec.CommandContext so that canceling the context also kills any running processes

- packages/zypper.go
- packages/zypper_test.go
patch info command requires a patch name to be provided. When there is no such argument provided, the command errors out with exit code 3.
> Skip getting patch info when no patches are found.

- packages/zypper.go
- packages/zypper_test.go
In the zypper info conflict section, the package names used to contain the architecture details as well. It has recently changed in SLES 15, which breaks the current parsing logic.
sample conflict section
`
Conflicts   : [10]
libzypp.src < 17.27.0-12.1
libzypp.noarch < 17.27.0-12.1
libzypp.x86_64 < 17.27.0-12.1
libzypp-devel.x86_64 < 17.27.0-12.1
libzypp-devel.noarch < 17.27.0-12.1
zypper.src < 1.14.46-13.1
zypper.noarch < 1.14.46-13.1
zypper.x86_64 < 1.14.46-13.1
zypper-log < 1.14.46-13.1
zypper-needs-restarting < 1.14.46-13.1
`
Tested with unit tests
> Update Zypper patch info parsing

- packages/apt_deb.go
Return lower-case package name for better resilience to non-compliant .deb packages as some packages
do not always adhere to the Debian Policy and might have mix-cased names.
Debian package manager  will register the package with lower case anyway so use lower-case package name.
This is necessary because the compliance check is done between the .deb file descriptor value and the internal
package management db which registers a lower-cased name.
fixes #376
> Return lower-case package name

- agentconfig/agentconfig.go
- agentendpoint/config_task.go
- agentendpoint/config_task_test.go
- agentendpoint/patch_windows.go
- agentendpoint/reboot_windows.go
- config/exec_resource.go
- config/file_resource.go
- config/repository_resource.go
- ospatch/system_linux.go
- ospatch/system_test_stub.go
- ospatch/system_windows.go
- ospatch/updates_linux.go
- ospatch/updates_test_stub.go
- ospatch/updates_windows.go
- packages/cos.go
- packages/cos_stub.go
- packages/cos_test.go
- packages/stub_linux.go
- packages/stub_windows.go
- policies/recipes/steps_linux.go
- policies/recipes/steps_windows.go
During a config run there will now be clear info logs when actions are taken or after a check has been completed.
We need to remove repos that config is no longer managing, we do this by clearing out all unmanaged repos that match our naming.
Actually limit error messages to the 512 byte limit.
For the new logging, here is an example of info logs, errors are always logged at any of the satges.
Execution Resource (success case)
- Validation successful
- Check state: resource state is NON_COMPLIANT
- Enforcing desired state for resource
- Desired state enforcement is successful
- Check state post enforcement: resource state is COMPLIANT
Execution Resource (resource is already in desired state)
- Validation successful
- Check state: resource state is COMPLIANT
> Add more info logs, actually cleanup unmanaged repos

- agentconfig/agentconfig.go
- agentendpoint/inventory.go
- agentendpoint/inventory_test.go
Because we are appending a known number of packages we can preallocate a temporary slice which we then pass to append. This avoids the constant growing of the slice because of multiple append calls.
> ReportInventory: Fix bug in deb/rpm inventory, reduce calls to append

- agentconfig/agentconfig.go
- config/package_resource.go
- config/package_resource_test.go
- packages/msi_windows.go
- packages/stub_linux.go
Keep a cache of package info for config package resource so we don't need to download the package on every run
This cache is keyed to the source of the resource so multiple resources that use the exact same source will use the same cache item
On every run update the timestamp for each accessed item in the cache so that we can clean up the cache of items that have not been touched for >7 days
Failure modes are very forgiving and we just invalidate the entire cache if necessary which will result in redownloading packages and recreating the cache.
> Config: Add package info caching

- agentendpoint/agentendpoint.go
- main.go
We will retry RegisterAgent forever now, this will block other functions on first start but this is WAI as we can not do anything else until RegisterAgent has completed anyway
> Add retry logic for RegisterAgent

- agentendpoint/patch_linux.go
- agentendpoint/patch_linux_test.go
- e2e_tests/test_suites/patch/patch.go
- ospatch/apt_upgrade.go
- ospatch/exclude.go
- ospatch/googet_update.go
- ospatch/updates.go
- ospatch/updates_test.go
- ospatch/yum_update.go
- ospatch/zypper_patch.go
- ospatch/zypper_patch_test.go
- packages/yum.go
- packages/yum_test.go
Unify filtering of packages - change filtering in yum to not use filt…ering eagerly when listing packages (only yum supports this operation)
Add possibility to use regex to exclude packages, when the exclude value is contained in '/' treat it as a regex, i.e.: "/^abc.*xyz$/", the '/' character cannot be used inside a linux package name (only letters, numbers, .-+_) so we don't have a problem of name collisions between packages and regexes
We don't add regex excluding in windows because KB numbers are pretty arbitrary
> Add regex support to package exclusion in OS Patch

- e2e_tests/test_suites/patch/patch.go
- e2e_tests/test_suites/patch/test_setup.go
- e2e_tests/utils/utils.go
Apt-get to downgrade a package when using -y flag needs and additional --allow-downgrades flag
This new test should fail in the current state of the code and https://github.com/GoogleCloudPlatform/osconfig/pull/418 should fix that
> Create e2e test that runs apt-get in a state that makes it downgrade a package

- packages/apt_deb.go
- packages/apt_deb_test.go
Changed logic to recreate exec.CommandContext when retrying with a new flag
> Fix previous PR: exec.CommandContext cannot be reused

- agentendpoint/patch_linux_test.go
- ospatch/exclude.go
In Golang, foreach loop create only one variable per a whole loop.
It is unsafe to pass pointer to the variable, cause after the loop,
all pointers will point to last element in array.
To make code safe by design, function ospatch.CreateStringExclude,
refactored to copy pointer to a string before memorizing it.
> Fix exclude packages field processing

- e2e_tests/utils/utils.go
And update Ubuntu GCP images to be up to date with http://cloud/compute/docs/images/os-details#debian.
> Remove Debian 9 [EOL] from e2e tests image list

- e2e_tests/utils/utils.go
* Removed windows-20h2-core [EOL]
* Updated opensuse-leap, sles and ubuntu images
> Remove old images from e2e tests image list

- agentconfig/agentconfig.go
- agentconfig/agentconfig_test.go
Reverts GoogleCloudPlatform/osconfig#454
Reverting PR, as recently found usage of FQDN causing problem with wildcard certificate verification on Windows Server
> Revert "Call FQDN"

- agentendpoint/config_task.go
Skip repo clean-up, as there is no clear way how to find full list of repos, repos might be distributed across many tasks and there is no source of truth.
> Disable repos clean-up

- config/package_resource_test.go
- packages/apt_deb.go
- packages/apt_deb_test.go
Agent doesn't support interactive frontend, apt-get will always use default options in all interactions if DEBIAN_FRONTEND=noninteractive is set.
> Set DEBIAN_FRONTEND=noninteractive for apt-get interactions

- examples/OSPolicyAssignments/console/README.md
- examples/OSPolicyAssignments/console/win-ensure-openssh.yaml
- examples/OSPolicyAssignments/console/win-validation-powershell.yaml
OSPolicy examples refer to exit codes but what exit codes 100 and 101 mean is missing on all samples and in Readme.md
> Adding what exit codes mean for OS Config policy

- policies/yum.go
- policies/yum_test.go
This adds a `[main]` section to `google_osconfig_managed.repo` with `gpgcheck=1`.
The purpose is to avoid triggering security scanners that detect `.repo` files without `gpgcheck` enabled, which currently happens when the repo file contains no repositories (the agent does add `gpgcheck` but does so on a per-repository basis).
> Added [main] section with gpgcheck to the agent-managed repo file.

- packages/zypper.go
Tses and customers think this is a fatal error when it is actually expected. Changing debug messages to indicate that
> Change debug messages when parsing zypper patch output

- examples/OSPolicyAssignments/CIS/cis-level1-once-a-day-policy.yaml
Move examples from the CIS document to the examples folder in git
> docs(osconfig):add OS policy example for CIS scanning

- README.md
Replaced 'OS Patch Management' with 'Patch' and 'OS configuration management' with 'OS policies' per the recent name changes.
> Update feature names in the README file

- packages/zypper.go
- packages/zypper_test.go
Fix zypper patch info parser to handle 3 different cases for newer SUSE versions:
- Conflict packages that starts with `srcpackage:` (e.g. `srcpackage:ruby2.5 < 2.5.9-150000.4.29.1`)
- Conflict packages that has float version (e.g. `ruby2.5.noarch < 2.5.9-150000.4.29.1`)
- Conflict packages that the package name doen't contain the architecture details (e.g. `zypper-log < 1.14.64-150400.3.32.1`)
/cc @dowgird
> Fix zypper patch info parser to consider conflicts-pkgs float versions

- e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
- e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
zypper repo `test-repo` was not reachable when it is added as a `.repo` file in the test VM, and the agent failed to update the package from this repo according to the added policy. However, it works fine with a local VM.
Adding this repo using `zypper addrepo` command + `zypper refresh` after it fixed this issue for the tests.
/cc @dowgird
> Fix SUSE pkg-update and pkg-no-update e2e tests

- e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
As this package is a dependency package for `ed-1.1-3.3.el6.x86_64.rpm` which is used in Enterprise-Linux Recipe steps tests
/cc @dowgird
> Fix Enterprise Linux Recipe-Steps tests to install info dependency package in the startup-script

- config/repository_resource.go
- config/repository_resource_test.go
- policies/apt.go
- policies/apt_test.go
Fixes OSConfig-agent to read all the entities in a GPG file. Previously, only the first entity was processed.
/cc @dowgird
/cc @adjackura
> Enable OSConfig agent to read GPG keys files with multiple entities

- agentconfig/agentconfig.go
On Windows systems "Program files" folder is meant to contain immutable and executable files. In consequence on some Windows instances refuse to write OS Config state file in this location. We're changing the location of state file to the LocalApplicationData.
> OS Config windows state file location changed

- policies/apt.go
- policies/apt_test.go
/cc @dowgird
/cc @MarcMarc 
should fix this issue https://github.com/GoogleCloudPlatform/osconfig/issues/506
> Use signed-by keyring approach for apt repos in Debian 12+ and Ubuntu 24+

- .github/dependabot.yml
Enabling daily scanning of the gomod dependencies (direct and indirect)
> Initial config of dependabot for the dependency updates scanning

- .github/dependabot.yml
Removing the reviewer list to leverage the existing reviewer set
> Using the default reviewer set for PR approvals

- agentconfig/agentconfig.go
- agentendpoint/inventory.go
* Add enable-guest-attributes to the config.
* Write inventory to guest attributes only if guest attributes enabled.
> Write inventory to attributes only if enabled

- agentconfig/agentconfig.go
- main_windows.go
All files written by osconfig should be placed in AppData directory
local to the Windows VM.
> Fix for lock location

- e2e_tests/utils/utils.go
The main goal is to install a new test grid for executing tests on the testing (autopush) pkgs.
/cc @dowgird
/cc @burov
> Allow Apt & Yum e2e tests to pull osconfig-agent pkg from testing repos

- packages/apt_deb.go
- packages/apt_deb_test.go
- packages/cos_test.go
- packages/googet_test.go
- packages/packages.go
- packages/rpm_test.go
- packages/yum_test.go
- packages/zypper_test.go
* Add source name and version to PkgInfo structure.
* Refactor tests to make them more readable and improve coverage.
* Extract source name and version for dpkg packages.
> Extract source name and version for dpkg packages.

- e2e_tests/test_suites/inventory/test_setup.go
- e2e_tests/test_suites/inventoryreporting/test_setup.go
- e2e_tests/test_suites/patch/test_setup.go
- e2e_tests/utils/utils.go
EL7 reached EOL
/cc @YahiaBadr
> Remove RHEL-7 and CentOS-7 images from e2e tests

- e2e_tests/test_suites/guestpolicies/guest_policies_utils.go
> Fix GuestPolicies e2e tests for SLES-15 SP5 by removing zypper update from VMs startup script

- e2e_tests/test_suites/ospolicies/ospolicies_utils.go
> Fix OSPolicies e2e tests for SLES-15 SP5 by removing zypper update from VMs startup script

- config/repository_resource_test.go
- e2e_tests/test_suites/guestpolicies/guest_policies_test_data.go
- e2e_tests/utils/utils.go
- policies/apt_test.go
- Use gcsfuse pkg instead of osconfig-agent-test deprecated pkg for some e2e tests
- Fix fetching gpg key unit tests which is no longer has rapture key - only AR key
/cc @dowgird
/cc @MarcMarc
> Fix Debian-12 failing test by using gcsfuse pkg & Fix fetching gpg key unit tests

- presubmit_packagebuild/docker-image/build-container-img-cloudbuild.yaml
This trigger will be used for auto updating the presubmit test container image on every new commit
> Add a new CloudBuild trigger config-file

- policies/recipes/recipe.go
- policies/recipes/steps.go
- util/util.go
- util/util_test.go
Fix scanner issues:
[Incorrect conversion between integer types](https://github.com/GoogleCloudPlatform/osconfig/security/code-scanning/7)
[Arbitrary file access during archive extraction ("Zip Slip")](https://github.com/GoogleCloudPlatform/osconfig/security/code-scanning/6)
[Arbitrary file access during archive extraction ("Zip Slip")](https://github.com/GoogleCloudPlatform/osconfig/security/code-scanning/5)
[Arbitrary file access during archive extraction ("Zip Slip")](https://github.com/GoogleCloudPlatform/osconfig/security/code-scanning/4)
[Arbitrary file access during archive extraction ("Zip Slip")
](https://github.com/GoogleCloudPlatform/osconfig/security/code-scanning/3)
[Arbitrary file write extracting an archive containing symbolic …
> Scanners fixes

- agentendpoint/patch_task.go
- agentendpoint/task_state_test.go
`RebootCount` was used only for forcing post-patch reboots via `RebootConfig = always`, but incremented for every reboot. As a result, the forced post-patch reboot was skipped if pre-patch reboot was required.
Note that the rename should be fine, since reading the old state file will result with counter being reset (so worst case, we will have one additional restart, but not more)
Closes: #755
> Rename `RebootCount` to `PostPatchRebootCount` and only increment it for post-patch reboots.

- retryutil/retry.go
- retryutil/retry_test.go
* Write tests for retryutil package.
* Refactor RetryAPICall to simplify the code.
* Fix bug with error mapping in RetryAPICall.
I was not able to trigger the case with metadata.NotDefinedError in tests, i fix the logic, but i suspect we can get rid of this case.
> Add tests for retryutil package.

- agentendpoint/agentendpoint.go
- agentendpoint/inventory.go
- agentendpoint/inventory_test.go
* Introduce new function that compute hash that independent from the order of inventory items.
* Write tests for computeHash and computeStableHash functions.
* Benchmark computeHash and computeStableHash to be able to compare approaches.
Benchmark results: 
goos: linux
goarch: amd64
pkg: github.com/GoogleCloudPlatform/osconfig/agentendpoint
cpu: Intel(R) Xeon(R) CPU @ 2.20GHz
Benchmark_computeHash-24          	   93759	     12064 ns/op
Benchmark_computeStableHash-24    	   17388	     68429 ns/op
> Update hash computation algorithm

- retryutil/retry_test.go
See
>{Failed      retry_test.go:207: sleeper.Sleep, elapsed time 203.483272ms bigger than expected 200ms}
[source](https://oss.gprow.dev/view/gs/oss-prow/pr-logs/pull/GoogleCloudPlatform_osconfig/805/osconfig-presubmit-gotest/1912247155062476800)
> defaultSleeper: tolerate 10% difference to reduce test flakiness

- packages/rpm.go
- packages/rpm_test.go
- packages/testdata/centos-7-1.rpm-query-all.want
- packages/testdata/oracle-linux-8.rpm-query-all.want
- packages/testdata/rhel-9-1.rpm-query-all.want
- packages/testdata/rocky-8-1.rpm-query-all.want
- packages/testdata/sles-12-1.rpm-query-all.want
- pretty/pretty_test.go
For Arch and SourceName some packages might have "(none)" instead of empty string if value is not available, correct this behavior and set default value for the field if "(none)" presented.
> Fix rpm extractor, handle (none) value correctly.

- .gitignore
Introduced recently in https://github.com/GoogleCloudPlatform/osconfig/pull/835 during rebase.
Would be good to squash with #835 merge-commit to allow git GC clean it up from history
> Binary cleanup, add to .gitignore

- agentconfig/agentconfig.go
- agentconfig/agentconfig_test.go
- main.go
Fixed JSON identifier for the universe domain and moved initialization of DisableCloudLogging parameter after querying metadata.
> Bugfixes for OSConfig agent TPC awareness

- e2e_tests/test_runner/test_runner.go
- e2e_tests/test_suites/patch/patch.go
Changelist includes:
- Creating test runner to start unifying e2e test setup across different test suites. Test runner contains timeout and retry logic for tests,
- Changing OSPatch test suite to use the new runner.
> Add test runner for e2e tests and timeout for OSPatch test cases
